apiVersion: v1
kind: Service
metadata:
  name: jenkins-gke-project-service
  namespace: pro-dev
spec:
  type: NodePort
  selector:
    app: jenkins-gke-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30081